### ISSUE TITLE
/zh claim command doesnt when im on a horse

### ISSUE THREAD

**Issue by SylisMC** [Xibalba/ZHorse#112]
When off the horse it says "you need to be on a horse" and when off i get nothing and this error in my console. idk whats happening, but im OP on the server

`[03:20:46 INFO]: Sylis issued server command: /zh claim
[03:20:46 WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[03:20:46 WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[03:20:46 WARN]: java.lang.reflect.InvocationTargetException
[03:20:46 WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[03:20:46 WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[03:20:46 WARN]: 	at com.github.zedd7.zhorse.managers.CommandManager.onCommand(CommandManager.java:57)
[03:20:46 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
[03:20:46 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[03:20:46 WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704)
[03:20:46 WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1620)
[03:20:46 WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1460)
[03:20:46 WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[03:20:46 WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[03:20:46 WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9)
[03:20:46 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[03:20:46 WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[03:20:46 WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[03:20:46 WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896)
[03:20:46 WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[03:20:46 WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[03:20:46 WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[03:20:46 WARN]: 	at java.lang.Thread.run(Unknown Source)
[03:20:46 WARN]: Caused by: java.lang.UnsupportedOperationException: SuperPerms no group permissions.
[03:20:46 WARN]: 	at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96)
[03:20:46 WARN]: 	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:691)
[03:20:46 WARN]: 	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:703)
[03:20:46 WARN]: 	at com.github.zedd7.zhorse.managers.PermissionManager.getPrimaryGroup(PermissionManager.java:26)
[03:20:46 WARN]: 	at com.github.zedd7.zhorse.managers.ConfigManager.getGroupName(ConfigManager.java:306)
[03:20:46 WARN]: 	at com.github.zedd7.zhorse.managers.ConfigManager.getClaimsLimit(ConfigManager.java:48)
[03:20:46 WARN]: 	at com.github.zedd7.zhorse.commands.AbstractCommand.hasReachedClaimsLimit(AbstractCommand.java:344)
[03:20:46 WARN]: 	at com.github.zedd7.zhorse.commands.CommandClaim.execute(CommandClaim.java:43)
[03:20:46 WARN]: 	at com.github.zedd7.zhorse.commands.CommandClaim.<init>(CommandClaim.java:24)
[03:20:46 WARN]: 	... 21 more`

**Comment by SylisMC** [comment]
I fixed it by adding "permission: minecraft.command.help" to the config, Is there a way to just allow everyone aside from cheating with a permission everyone gets by default?
```visitor:
    color: <f>
    color-bypass: false
    claims-limit: 1
    permission: minecraft.command.help

**Comment by Zedd7** [comment]
Currently, ZHorse only support permissions systems that provide permission groups.
This will be changed as of version 2.0.0 (see #104).

So for now you have to trick it by using the 'fake/surrogate' group system provided for the case where you'd want to use different zh's group names than those existing in your permission system.

For the record, you can use any permission such as `zh.<name-of-the-group>` instead of `minecraft.command.help` and give it to whoever you want.
That allows you to configure different colors/limits for different players.
