### ISSUE TITLE
Error when /zh claim or /zh tame

### ISSUE THREAD

**Issue by SiennaWesty** [Xibalba/ZHorse#143]
Can't seem to claim or tame horses

If you need anymore info please let me know, thanks very much!

### Console output 

[02:25:02] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[02:25:02] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[02:25:02] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[02:25:02] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[02:25:02] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[02:25:02] [Server thread/WARN]: 	at com.github.zedd7.zhorse.managers.CommandManager.onCommand(CommandManager.java:47)
[02:25:02] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[02:25:02] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148)
[02:25:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:734)
[02:25:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1653)
[02:25:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1510)
[02:25:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(SourceFile:36)
[02:25:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(SourceFile:9)
[02:25:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[02:25:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
[02:25:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
[02:25:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[02:25:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
[02:25:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:901)
[02:25:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:894)
[02:25:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
[02:25:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:878)
[02:25:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:817)
[02:25:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:155)
[02:25:02] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[02:25:02] [Server thread/WARN]: Caused by: java.lang.UnsupportedOperationException: SuperPerms no group permissions.
[02:25:02] [Server thread/WARN]: 	at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96)
[02:25:02] [Server thread/WARN]: 	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:679)
[02:25:02] [Server thread/WARN]: 	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:691)
[02:25:02] [Server thread/WARN]: 	at com.github.zedd7.zhorse.managers.PermissionManager.getPrimaryGroup(PermissionManager.java:32)
[02:25:02] [Server thread/WARN]: 	at com.github.zedd7.zhorse.managers.ConfigManager.getGroupName(ConfigManager.java:307)
[02:25:02] [Server thread/WARN]: 	at com.github.zedd7.zhorse.managers.ConfigManager.getClaimsLimit(ConfigManager.java:47)
[02:25:02] [Server thread/WARN]: 	at com.github.zedd7.zhorse.commands.AbstractCommand.hasReachedClaimsLimit(AbstractCommand.java:339)
[02:25:02] [Server thread/WARN]: 	at com.github.zedd7.zhorse.commands.CommandClaim.execute(CommandClaim.java:43)
[02:25:02] [Server thread/WARN]: 	at com.github.zedd7.zhorse.commands.CommandClaim.<init>(CommandClaim.java:24)
[02:25:02] [Server thread/WARN]: 	... 24 more
[02:25:05] [Server thread/INFO]: SiennaMisa issued server command: /zh claim shadowfax
[02:25:05] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[02:25:05] [Server thread/WARN]: 	at sun.reflect.GeneratedConstructorAccessor100.newInstance(Unknown Source)
[02:25:05] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[02:25:05] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[02:25:05] [Server thread/WARN]: 	at com.github.zedd7.zhorse.managers.CommandManager.onCommand(CommandManager.java:47)
[02:25:05] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[02:25:05] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148)
[02:25:05] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:734)
[02:25:05] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1653)
[02:25:05] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1510)
[02:25:05] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(SourceFile:36)
[02:25:05] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(SourceFile:9)
[02:25:05] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[02:25:05] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
[02:25:05] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
[02:25:05] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[02:25:05] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
[02:25:05] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:901)
[02:25:05] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:894)
[02:25:05] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeAll(SourceFile:103)
[02:25:05] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:877)
[02:25:05] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:817)
[02:25:05] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:155)
[02:25:05] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[02:25:05] [Server thread/WARN]: Caused by: java.lang.UnsupportedOperationException: SuperPerms no group permissions.
[02:25:05] [Server thread/WARN]: 	at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96)
[02:25:05] [Server thread/WARN]: 	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:679)
[02:25:05] [Server thread/WARN]: 	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:691)
[02:25:05] [Server thread/WARN]: 	at com.github.zedd7.zhorse.managers.PermissionManager.getPrimaryGroup(PermissionManager.java:32)
[02:25:05] [Server thread/WARN]: 	at com.github.zedd7.zhorse.managers.ConfigManager.getGroupName(ConfigManager.java:307)
[02:25:05] [Server thread/WARN]: 	at com.github.zedd7.zhorse.managers.ConfigManager.getClaimsLimit(ConfigManager.java:47)
[02:25:05] [Server thread/WARN]: 	at com.github.zedd7.zhorse.commands.AbstractCommand.hasReachedClaimsLimit(AbstractCommand.java:339)
[02:25:05] [Server thread/WARN]: 	at com.github.zedd7.zhorse.commands.CommandClaim.execute(CommandClaim.java:43)
[02:25:05] [Server thread/WARN]: 	at com.github.zedd7.zhorse.commands.CommandClaim.<init>(CommandClaim.java:24)
[02:25:05] [Server thread/WARN]: 	... 23 more
[02:25:09] [Server thread/INFO]: SiennaMisa issued server command: /zh tame

- Server version : 1.16.1 Minecraft

- ZHorse version : /zh claim /zh tame

**Comment by Zedd7** [comment]
Hello, this issue indeed lacks some information but, from what I can read, it looks like your permission manager plugin is not capable of handling primary groups, which is a requisite of ZHorse.
Try with another permission manager (it can be as simple as BukkitPermission, for instance) and see if it happens again.

**Comment by SiennaWesty** [comment]
@Zedd7 Thanks very much I will try this when we get home, I'll let you know how it goes
