### ISSUE TITLE
This stack floods my server

### ISSUE THREAD

**Issue by Eredrim** [Xibalba/ZHorse#16]
```
[00:56:07] [Server thread/WARN]: java.lang.NullPointerException
[00:56:07] [Server thread/WARN]: 	at eu.reborn_minecraft.zhorse.utils.SQLDatabaseConnector.hasResult(SQLDatabaseConnector.java:112)
[00:56:07] [Server thread/WARN]: 	at eu.reborn_minecraft.zhorse.managers.DataManager.isHorseRegistered(DataManager.java:222)
[00:56:07] [Server thread/WARN]: 	at eu.reborn_minecraft.zhorse.utils.DelayedChunckUnload$1.run(DelayedChunckUnload.java:20)
[00:56:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[00:56:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[00:56:07] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730)
[00:56:07] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[00:56:07] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
[00:56:07] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
[00:56:07] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```
And it is annoying...

**Comment by Zedd7** [comment]
Spigot version ? Minecraft version ? ZHorse version ? Database type ?

**Comment by Eredrim** [comment]
Minecraft 1.11
Spigot git-Spigot-f950f8e-622630c
ZHorse 1.6.3
Database MySQL

**Comment by Zedd7** [comment]
Is there any ZHorse-related errors on server startup ?
Did you just install ZHorse or was is running fine for a while ?
Does it happen with SQLite too ?

**Comment by Eredrim** [comment]
It was just a typing error in my config file. The MySQL server url was not right. Maybe you could create more explicit message in this case ?

**Comment by Zedd7** [comment]
That was what I expected and I'll see what I can do to enhance errors display.
The issue is that when any parameter is not correct, MySQL driver just says "error".
