### ISSUE TITLE
Many NullPointerException in DataManager.hasLocationChanged

### ISSUE THREAD

**Issue by taberruu** [Xibalba/ZHorse#20]
Hey,
I get a lot of NullPointerException in my console.

Can you look at this?

`java.lang.NullPointerException
at eu.reborn_minecraft.zhorse.managers.DataManager.hasLocationChanged(DataManager.java:189) ~[?:?]
at eu.reborn_minecraft.zhorse.managers.DataManager.updateHorseLocation(DataManager.java:313) ~[?:?]
at eu.reborn_minecraft.zhorse.utils.DelayedChunckLoad$1.run(DelayedChunckLoad.java:22) ~[?:?]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-7d78b81-d5e7885]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-7d78b81-d5e7885]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot.jar:git-Spigot-7d78b81-d5e7885]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-7d78b81-d5e7885]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot.jar:git-Spigot-7d78b81-d5e7885]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot.jar:git-Spigot-7d78b81-d5e7885]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]`

My setup:

>about
This server is running CraftBukkit version git-Spigot-7d78b81-d5e7885 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
You are running the latest version

>about zhorse
ZHorse version 1.6.3
This plugin provides an enhanced management of horses
Author: Z3dd7

Database Type: SQLite

**Comment by Zedd7** [comment]
Hi, did you just install ZHorse or have you been running it for a while ?

**Comment by taberruu** [comment]
Hey, 
It's been running for a while.

**Comment by Zedd7** [comment]
At first look it appears that the location of one or several horses is missing from the database.
If you know how to use SQLite you can check for a missing entry in the columns horse.locationX/Y/Z/World.
If not, you can send me (MP if you want) your ZHorse.db file and I will take a look.

**Comment by taberruu** [comment]
Thank you, 
Yes, there are many horses in a world that no longer exists.
But the Admin Delete Command can't get rid, because getChunk crashes as well.

Will you implement a workaround?
Otherwise, a better logging would be good, to see & manual delete the concerned horseIds.

**Comment by Zedd7** [comment]
I have plans for a logging system but I cannot work on any of this currently because of my exams.
I will take a closer look at this in the end of the month
