### ISSUE TITLE
Could not pass event EntityPortalEvent to ZHorse v1.6.3

### ISSUE THREAD

**Issue by taberruu** [Xibalba/ZHorse#22]
Hey,
We found the next error ....

`[18:27:00 ERROR]: Could not pass event EntityPortalEvent to ZHorse v1.6.3
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-7d78b81-27dd3ca]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-7d78b81-27dd3ca]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-7d78b81-27dd3ca]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-7d78b81-27dd3ca]
        at net.minecraft.server.v1_11_R1.Entity.c(Entity.java:2223) [spigot.jar:git-Spigot-7d78b81-27dd3ca]
        at net.minecraft.server.v1_11_R1.BlockEnderPortal.a(BlockEnderPortal.java:46) [spigot.jar:git-Spigot-7d78b81-27dd3ca]
        at net.minecraft.server.v1_11_R1.Entity.checkBlockCollisions(Entity.java:903) [spigot.jar:git-Spigot-7d78b81-27dd3ca]
        at net.minecraft.server.v1_11_R1.Entity.move(Entity.java:486) [spigot.jar:git-Spigot-7d78b81-27dd3ca]
        at net.minecraft.server.v1_11_R1.EntityLiving.g(EntityLiving.java:1762) [spigot.jar:git-Spigot-7d78b81-27dd3ca]
        at net.minecraft.server.v1_11_R1.EntityHorseAbstract.g(EntityHorseAbstract.java:707) [spigot.jar:git-Spigot-7d78b81-27dd3ca]
        at net.minecraft.server.v1_11_R1.EntityLiving.n(EntityLiving.java:2064) [spigot.jar:git-Spigot-7d78b81-27dd3ca]
        at net.minecraft.server.v1_11_R1.EntityInsentient.n(EntityInsentient.java:501) [spigot.jar:git-Spigot-7d78b81-27dd3ca]
        at net.minecraft.server.v1_11_R1.EntityAgeable.n(EntityAgeable.java:158) [spigot.jar:git-Spigot-7d78b81-27dd3ca]
        at net.minecraft.server.v1_11_R1.EntityAnimal.n(EntityAnimal.java:24) [spigot.jar:git-Spigot-7d78b81-27dd3ca]
        at net.minecraft.server.v1_11_R1.EntityHorseAbstract.n(EntityHorseAbstract.java:489) [spigot.jar:git-Spigot-7d78b81-27dd3ca]
        at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1893) [spigot.jar:git-Spigot-7d78b81-27dd3ca]
        at net.minecraft.server.v1_11_R1.EntityInsentient.A_(EntityInsentient.java:244) [spigot.jar:git-Spigot-7d78b81-27dd3ca]
        at net.minecraft.server.v1_11_R1.EntityHorseAbstract.A_(EntityHorseAbstract.java:526) [spigot.jar:git-Spigot-7d78b81-27dd3ca]
        at net.minecraft.server.v1_11_R1.EntityHorse.A_(SourceFile:208) [spigot.jar:git-Spigot-7d78b81-27dd3ca]
        at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1629) [spigot.jar:git-Spigot-7d78b81-27dd3ca]
        at net.minecraft.server.v1_11_R1.World.h(World.java:1604) [spigot.jar:git-Spigot-7d78b81-27dd3ca]
        at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1430) [spigot.jar:git-Spigot-7d78b81-27dd3ca]
        at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:617) [spigot.jar:git-Spigot-7d78b81-27dd3ca]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:806) [spigot.jar:git-Spigot-7d78b81-27dd3ca]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-7d78b81-27dd3ca]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot.jar:git-Spigot-7d78b81-27dd3ca]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot.jar:git-Spigot-7d78b81-27dd3ca]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
        at eu.reborn_minecraft.zhorse.managers.EventManager.onEntityPortal(EventManager.java:156) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor633.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-7d78b81-27dd3ca]
        ... 27 more`

Latest Spigot.
Within 90 Seconds 170 000 Lines Console Spam (Only by ZHorse)

**Comment by Zedd7** [comment]
Do you have any plugin managing portals ?

**Comment by taberruu** [comment]
Only Multiverse-Portals, which is kind of default for a spigot server

**Comment by Zedd7** [comment]
Indeed, my question was badly formulated.
I wanted to know if you have another plugin that handle portal event like HorseTpWithMe but, after a second thought, it should not matter here.

**Comment by taberruu** [comment]
Any progress?
My last log file was 31 MB in 2 hours...

**Comment by Zedd7** [comment]
I just finished my exam session today so I'll get back on ZHorse tomorrow.

**Comment by Zedd7** [comment]
Hello, I started working on this issue today and it appears that the destination of a portal teleportation cannot be retrieved when a claimed horse walks trough an ender portal block.

I tried to reproduce it on my server (with the very last versions of Spigot, ZHorse, Vault) but without success.
I tried to : 
- Enable/disable the source/destination world + their crossable parameters in config
- Force the horse to walk trough an ender portal block by using a leash
- Ride it myself through the portal

In all those cases, no exception occurred and the teleportation was cancelled (or not) accordingly to the config.

So here is a debug version of ZHorse 1.6.4 snapshot 1 : https://www.mediafire.com/?7ueftlumfmefhl9
It warps the sensitive block of code that was throwing exceptions to catch them and display a custom debug message. (3-4 lines)
If you manage to find a method to reproduce this bug everytime (possibly only on your server), it can help.

By the way the spam is caused by the fact that the event is fired at every tick (or several) when a horse is standing in a portal block.

**Comment by Zedd7** [comment]
Does this error still occur ?

**Comment by taberruu** [comment]
Sorry for the late reply.
I can't test that anymore.
We have had to exchange the plugin because our players had too many problems with it.

**Comment by Zedd7** [comment]
No problem.
I will keep open the issues that you created but are relevant for other servers, so feel free to unsubscribe from the notifications.
