### ISSUE TITLE
New SQL errors in 1.6.4

### ISSUE THREAD

**Issue by Eredrim** [Xibalba/ZHorse#36]
Hello,

I meet new SQL errors in your latest release. Please see below : 

```
[12:42:47] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 36 778 448 milliseconds ago.  The last packet sent successfully to the server was 36 778 452 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
[12:42:47] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[12:42:47] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[12:42:47] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[12:42:47] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[12:42:47] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[12:42:47] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989)
[12:42:47] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3743)
[12:42:47] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2506)
[12:42:47] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677)
[12:42:47] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
[12:42:47] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2503)
[12:42:47] [Server thread/WARN]: 	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1369)
[12:42:47] [Server thread/WARN]: 	at com.gmail.xibalbazedd.zhorse.database.SQLDatabaseConnector.hasResult(SQLDatabaseConnector.java:142)
[12:42:47] [Server thread/WARN]: 	at com.gmail.xibalbazedd.zhorse.managers.DataManager.isPlayerRegistered(DataManager.java:298)
[12:42:47] [Server thread/WARN]: 	at com.gmail.xibalbazedd.zhorse.utils.PlayerJoin.<init>(PlayerJoin.java:16)
[12:42:47] [Server thread/WARN]: 	at com.gmail.xibalbazedd.zhorse.managers.EventManager.onPlayerJoin(EventManager.java:252)
[12:42:47] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:42:47] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[12:42:47] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:42:47] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[12:42:47] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[12:42:47] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[12:42:47] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[12:42:47] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[12:42:47] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerList.onPlayerJoin(PlayerList.java:327)
[12:42:47] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:160)
[12:42:47] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.LoginListener.b(LoginListener.java:147)
[12:42:47] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.LoginListener.F_(LoginListener.java:57)
[12:42:47] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233)
[12:42:47] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140)
[12:42:47] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:842)
[12:42:47] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[12:42:47] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[12:42:47] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[12:42:47] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[12:42:47] [Server thread/WARN]: Caused by: java.net.SocketException: Broken pipe
[12:42:47] [Server thread/WARN]: 	at java.net.SocketOutputStream.socketWrite0(Native Method)
[12:42:47] [Server thread/WARN]: 	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
[12:42:47] [Server thread/WARN]: 	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
[12:42:47] [Server thread/WARN]: 	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
[12:42:47] [Server thread/WARN]: 	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
[12:42:47] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3725)
[12:42:47] [Server thread/WARN]: 	... 28 more
```

```
[12:42:47] [Craft Scheduler Thread - 2/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '9bbe5afa-ab5d-3255-9881-d12b7bf9815a' for key 'PRIMARY'
[12:42:47] [Craft Scheduler Thread - 2/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[12:42:47] [Craft Scheduler Thread - 2/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[12:42:47] [Craft Scheduler Thread - 2/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[12:42:47] [Craft Scheduler Thread - 2/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[12:42:47] [Craft Scheduler Thread - 2/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[12:42:47] [Craft Scheduler Thread - 2/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
[12:42:47] [Craft Scheduler Thread - 2/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:935)
[12:42:47] [Craft Scheduler Thread - 2/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)
[12:42:47] [Craft Scheduler Thread - 2/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)
[12:42:47] [Craft Scheduler Thread - 2/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[12:42:47] [Craft Scheduler Thread - 2/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677)
[12:42:47] [Craft Scheduler Thread - 2/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
[12:42:47] [Craft Scheduler Thread - 2/WARN]: 	at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1540)
[12:42:47] [Craft Scheduler Thread - 2/WARN]: 	at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2595)
[12:42:47] [Craft Scheduler Thread - 2/WARN]: 	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1468)
[12:42:47] [Craft Scheduler Thread - 2/WARN]: 	at com.gmail.xibalbazedd.zhorse.database.SQLDatabaseConnector.executeUpdate(SQLDatabaseConnector.java:55)
[12:42:47] [Craft Scheduler Thread - 2/WARN]: 	at com.gmail.xibalbazedd.zhorse.managers.DataManager.registerPlayer(DataManager.java:369)
[12:42:47] [Craft Scheduler Thread - 2/WARN]: 	at com.gmail.xibalbazedd.zhorse.utils.PlayerJoin$1.run(PlayerJoin.java:22)
[12:42:47] [Craft Scheduler Thread - 2/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[12:42:47] [Craft Scheduler Thread - 2/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[12:42:47] [Craft Scheduler Thread - 2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[12:42:47] [Craft Scheduler Thread - 2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[12:42:47] [Craft Scheduler Thread - 2/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

After the two first ones, this error was raised in loop.
```
[12:45:21] [Craft Scheduler Thread - 57/WARN]: java.sql.SQLException: Column count doesn't match value count at row 1
[12:45:21] [Craft Scheduler Thread - 57/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
[12:45:21] [Craft Scheduler Thread - 57/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)
[12:45:21] [Craft Scheduler Thread - 57/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)
[12:45:21] [Craft Scheduler Thread - 57/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[12:45:21] [Craft Scheduler Thread - 57/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677)
[12:45:21] [Craft Scheduler Thread - 57/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
[12:45:21] [Craft Scheduler Thread - 57/WARN]: 	at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1540)
[12:45:21] [Craft Scheduler Thread - 57/WARN]: 	at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2595)
[12:45:21] [Craft Scheduler Thread - 57/WARN]: 	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1468)
[12:45:21] [Craft Scheduler Thread - 57/WARN]: 	at com.gmail.xibalbazedd.zhorse.database.SQLDatabaseConnector.executeUpdate(SQLDatabaseConnector.java:55)
[12:45:21] [Craft Scheduler Thread - 57/WARN]: 	at com.gmail.xibalbazedd.zhorse.managers.DataManager.registerHorseInventory(DataManager.java:331)
[12:45:21] [Craft Scheduler Thread - 57/WARN]: 	at com.gmail.xibalbazedd.zhorse.managers.DataManager.updateHorseInventory(DataManager.java:452)
[12:45:21] [Craft Scheduler Thread - 57/WARN]: 	at com.gmail.xibalbazedd.zhorse.managers.HorseManager$1.run(HorseManager.java:178)
[12:45:21] [Craft Scheduler Thread - 57/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[12:45:21] [Craft Scheduler Thread - 57/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[12:45:21] [Craft Scheduler Thread - 57/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[12:45:21] [Craft Scheduler Thread - 57/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[12:45:21] [Craft Scheduler Thread - 57/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

Regards,

**Comment by Zedd7** [comment]
Hi, the last two exceptions are related to the first one. It seems that MySQL connection failures are still a thing.
I will post a snapshot here to make a fix attempt. (few hours/days, can't tell)

**Comment by Eredrim** [comment]
Ok, thanks a lot.

**Comment by Zedd7** [comment]
Also, did use /zh reload at some point after starting your server and before these errors were raised ?

**Comment by Eredrim** [comment]
No errors happen without typing any command.

**Comment by Zedd7** [comment]
So, the important part of the error is this one :
> The last packet successfully received from the server was 36 778 448 milliseconds ago.  The last packet sent successfully to the server was 36 778 452 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.

I have already enabled the "autoReconnect" option and also set the "maxReconnects" option to 10.
So I guess that your local "wait_timeout" option is somewhat low and keeps disconnecting ZHorse.
After 10 times, ZHorse is no longer allowed to reconnect and outputs this error in your console.

Here is a guide to modify the "wait_timeout" parameter. Please tell me what is the current value of that option, then try changing it to see if it fixes your issue.

**Comment by Zedd7** [comment]
If it doesn't work, I added a homemade reconnect feature in this snapshot : http://www.mediafire.com/file/9cqv4nzw92wvc0w/ZHorse+1.6.5+snapshot+1.jar

**Comment by Eredrim** [comment]
The strange fact was I hadn't this kind of problem with 1.6.4 snapshot 4 (after to have updated my spigot version). 
About my auto_reconnect option, I don't know the value of this option because my mysql server is hosted and administrated on a mutualised server. So I can't see or modify any option. In consequences, I have just uploaded your new snapshot and I keep you informed tomorrow if it works.

**Comment by Eredrim** [comment]
I continue to have this exception with the latest snapshot : 
```
[00:17:00] [Craft Scheduler Thread - 13/WARN]: java.sql.SQLException: Column count doesn't match value count at row 1
[00:17:00] [Craft Scheduler Thread - 13/WARN]: at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
[00:17:00] [Craft Scheduler Thread - 13/WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)
[00:17:00] [Craft Scheduler Thread - 13/WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)
[00:17:00] [Craft Scheduler Thread - 13/WARN]: at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[00:17:00] [Craft Scheduler Thread - 13/WARN]: at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677)
[00:17:00] [Craft Scheduler Thread - 13/WARN]: at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)
[00:17:00] [Craft Scheduler Thread - 13/WARN]: at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
[00:17:00] [Craft Scheduler Thread - 13/WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
[00:17:00] [Craft Scheduler Thread - 13/WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
[00:17:00] [Craft Scheduler Thread - 13/WARN]: at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5098)
[00:17:00] [Craft Scheduler Thread - 13/WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
[00:17:00] [Craft Scheduler Thread - 13/WARN]: at com.gmail.xibalbazedd.zhorse.database.SQLDatabaseConnector.executeUpdate(SQLDatabaseConnector.java:71)
[00:17:00] [Craft Scheduler Thread - 13/WARN]: at com.gmail.xibalbazedd.zhorse.managers.DataManager.registerHorseInventory(DataManager.java:342)
[00:17:00] [Craft Scheduler Thread - 13/WARN]: at com.gmail.xibalbazedd.zhorse.managers.DataManager.updateHorseInventory(DataManager.java:474)
[00:17:00] [Craft Scheduler Thread - 13/WARN]: at com.gmail.xibalbazedd.zhorse.managers.HorseManager$1.run(HorseManager.java:178)
[00:17:00] [Craft Scheduler Thread - 13/WARN]: at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[00:17:00] [Craft Scheduler Thread - 13/WARN]: at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[00:17:00] [Craft Scheduler Thread - 13/WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[00:17:00] [Craft Scheduler Thread - 13/WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[00:17:00] [Craft Scheduler Thread - 13/WARN]: at java.lang.Thread.run(Thread.java:745)
```

**Comment by Zedd7** [comment]
This is a SQLException, not a CommunicationException. I will check that tomorrow.

**Comment by Zedd7** [comment]
It says that that the structure of your inventory_item table is not the same as the one used by the code.
The actual structure is the following : 
> uuid VARCHAR(36) NOT NULL,
   slot INT NOT NULL,
   data TEXT NOT NULL,

This issue might be inherited from when you used snapshot 4 of 1.6.4 which had a different table structure for inventories.
Try to execute the following SQL updates on your database (I assume that you don't use prefixes) : 
`USE zhorse;`
`DROP TABLE IF EXISTS horse_stats;`
`DROP TABLE IF EXISTS inventory_item;`
`DROP TABLE IF EXISTS horse_inventory;`

Horse resurrection is not implemented yet so clearing those tables is fine.
Do it while your server is offline to be on the safe side !

**Comment by Eredrim** [comment]
I deleted the tables as you recommended to me. I'll keep you informed of the result.

**Comment by Eredrim** [comment]
Good news, it seems to be work. Nice shot !
