### ISSUE TITLE
URGENT - ConcurrentModificationException error when /zh here

### ISSUE THREAD

**Issue by Oruss7** [Xibalba/ZHorse#5]
```
[15:05:08] [Server thread/INFO]: Oruss7 issued server command: /zh here
[15:05:11] [Server thread/ERROR]: Encountered an unexpected exception
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429) ~[?:1.8.0_60]
    at java.util.HashMap$KeyIterator.next(HashMap.java:1453) ~[?:1.8.0_60]
    at net.minecraft.server.v1_10_R1.EntityTracker.updatePlayers(EntityTracker.java:176) ~[spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:821) ~[spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) ~[spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) ~[spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [spigot-1.10.2.jar:git-Spigot-7745d45-02d704b]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
[15:05:11] [Server thread/ERROR]: This crash report has been saved to: /home/a882013062922551229/29699/./crash-reports/crash-2016-08-21_15.05.11-server.txt
[15:05:11] [Server thread/INFO]: Stopping server
```

I thinks you use an shared hashmap between threads ^^

**Comment by Zedd7** [comment]
Hi, could you specify your ZHorse and Java version ?

**Comment by Oruss7** [comment]
sure, 
- ZHorse v1.5.2 snapshot
- Java 8

**Comment by Zedd7** [comment]
Sorry, I saw the /zh here command and the HashMap exception so I immediately thought that it occured inside ZHorse's code but it is actually 100% Spigot code here.

Did it happen more than once ? And since when do you use ZHorse ?
If it happens again tell me and I will open a ticket on spigot ;)

**Comment by Oruss7** [comment]
my spigot version: 
CraftBukkit version git-Spigot-7745d45-02d704b (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT) You are 32 version(s) behind

I can't use zhorse, this error occurs when player tape /zh here and the server crash 3 min after...

**Comment by Zedd7** [comment]
Ok if it happen everytime I'll open a ticket on spigot, but again I can't do anything about that from my own code :/

**Comment by Oruss7** [comment]
Thanks. keep me informed.

**Comment by Oruss7** [comment]
have you open an issues on spigot Jira ?

**Comment by Zedd7** [comment]
Not yet, I have too much work this week to track a ticket

**Comment by Oruss7** [comment]
let's me open it. What can i say?
I need to use your plugin, it's the best.

**Comment by Zedd7** [comment]
Of course you can open it, just tell me if details on how /zh here works are needed ;)

**Comment by Oruss7** [comment]
https://hub.spigotmc.org/jira/browse/SPIGOT-2624

**Comment by Oruss7** [comment]
Please fix your plugin or tell me how reproduce bug without your plugin if it's a spigot bug.
See the spigot Jira issue. 

Thanks !

**Comment by Zedd7** [comment]
Well, /zh here works as follow : 
1. Spawn a new horse at the target location
2. Customize the new horse so it's exactly like the old one
3. Copy the inventory of the old horse to the new one
4. Remove the old horse

If you manage to reproduce this (use ZHorse's code), maybe the bug will happen again.
However you are the first ever to report this, and I talk frequently to several admins of servers running ZHorse :/

**Comment by Oruss7** [comment]
what can i do?
Both spigot and you can fix the problem. 

This error crash my server. I can't use your plugin if this bug is not solved.
Spigot dev seems to think, it's a plugin isssue. You, a spigot issue.

This error only appears when many players are online. I can't  reproduce it myself...

**Comment by Zedd7** [comment]
I can't reproduce it either and apparently ZHorse's code is not involved, so how could I fix it ?

**Comment by Oruss7** [comment]
How reproduce:
- open spigot server with 2 people
- use /zh here
  if no error, try ~10

**Comment by Zedd7** [comment]
Dude it's my plugin so you can be sure that I tried it with 1-30 people, on Win/Linux, vanilla or not, and with every minecraft/spigot version :p
