### ISSUE TITLE
Zhorse Claim problem

### ISSUE THREAD

**Issue by ghost** [Xibalba/ZHorse#56]
So I am using spigot 1.11.2-r01 and the latest version of your plugin and whenever I try to run a command like /zhorse claim nothing happens. When I look at the command prompt for my server it looks like the entire plugin broke and I get an entire page of errors. Using Vault 1.5.3 currently.

`[22:00:37] [Server thread/INFO]: freedomna issued server command: /zh claim
[22:00:37] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[22:00:37] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[22:00:37] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[22:00:37] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[22:00:37] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[22:00:37] [Server thread/WARN]: 	at com.gmail.xibalbazedd.zhorse.managers.CommandManager.onCommand(CommandManager.java:40)
[22:00:37] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[22:00:37] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[22:00:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
[22:00:37] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1354)
[22:00:37] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1189)
[22:00:37] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[22:00:37] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[22:00:37] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[22:00:37] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[22:00:37] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[22:00:37] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[22:00:37] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
[22:00:37] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[22:00:37] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[22:00:37] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[22:00:37] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[22:00:37] [Server thread/WARN]: Caused by: java.lang.UnsupportedOperationException: SuperPerms no group permissions.
[22:00:37] [Server thread/WARN]: 	at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96)
[22:00:37] [Server thread/WARN]: 	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:726)
[22:00:37] [Server thread/WARN]: 	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:738)
[22:00:37] [Server thread/WARN]: 	at com.gmail.xibalbazedd.zhorse.managers.PermissionManager.getPrimaryGroup(PermissionManager.java:26)
[22:00:37] [Server thread/WARN]: 	at com.gmail.xibalbazedd.zhorse.managers.ConfigManager.getGroupName(ConfigManager.java:284)
[22:00:37] [Server thread/WARN]: 	at com.gmail.xibalbazedd.zhorse.managers.ConfigManager.getClaimsLimit(ConfigManager.java:53)
[22:00:37] [Server thread/WARN]: 	at com.gmail.xibalbazedd.zhorse.commands.AbstractCommand.hasReachedClaimsLimit(AbstractCommand.java:278)
[22:00:37] [Server thread/WARN]: 	at com.gmail.xibalbazedd.zhorse.commands.CommandClaim.execute(CommandClaim.java:41)
[22:00:37] [Server thread/WARN]: 	at com.gmail.xibalbazedd.zhorse.commands.CommandClaim.<init>(CommandClaim.java:22)
[22:00:37] [Server thread/WARN]: 	... 21 more`

I do not use any permission plugin as the server is just for me and friends and we are all equal.

**Comment by Zedd7** [comment]
Please use pastebin for server logs : http://https://pastebin.com/

**Comment by ghost** [comment]
My apologies:
https://pastebin.com/UkijCutG

**Comment by Zedd7** [comment]
I can confirm that it happens because you don't have any permission plugin. You will need to install one (like PermissionBukkit) and configure it in order to run ZHorse.

BTW, long errors logs are perfectly normal. They just list the steps that lead to the error.
