### ISSUE TITLE
HorseManager removeHorse not thread-safe

### ISSUE THREAD

**Issue by 3ventic** [Xibalba/ZHorse#9]
[`removeHorse` in HorseManager](https://github.com/Xibalba/ZHorse/blob/0dd9b5679412381fb7938be4aa9411867530e16d/src/eu/reborn_minecraft/zhorse/managers/HorseManager.java#L165) calls bukkit APIs in a secondary thread, which [is not thread-safe and should not be done](http://wiki.bukkit.org/Scheduler_Programming#Tips_for_thread_safety).

```
[17:58:27] [Server thread/INFO]: 3ventic issued server command: /zh here
[17:58:30] [Thread-17/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns
[17:58:30] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.MCUtil.ensureMain(MCUtil.java:40)
[17:58:30] [Thread-17/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[17:58:30] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:158)
[17:58:30] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:141)
[17:58:30] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137)
[17:58:30] [Thread-17/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.getChunkAt(CraftWorld.java:149)
[17:58:30] [Thread-17/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.getChunkAt(CraftWorld.java:591)
[17:58:30] [Thread-17/WARN]:    at eu.reborn_minecraft.zhorse.managers.HorseManager.getChunksInRegion(HorseManager.java:246)
[17:58:30] [Thread-17/WARN]:    at eu.reborn_minecraft.zhorse.managers.HorseManager.access$0(HorseManager.java:238)
[17:58:30] [Thread-17/WARN]:    at eu.reborn_minecraft.zhorse.managers.HorseManager$1.run(HorseManager.java:180)
[17:58:30] [Thread-17/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns
[17:58:30] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.MCUtil.ensureMain(MCUtil.java:40)
[17:58:30] [Thread-17/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[17:58:30] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:158)
[17:58:30] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:141)
[17:58:30] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137)
[17:58:30] [Thread-17/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.getChunkAt(CraftWorld.java:149)
[17:58:30] [Thread-17/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.getChunkAt(CraftWorld.java:591)
[17:58:30] [Thread-17/WARN]:    at eu.reborn_minecraft.zhorse.managers.HorseManager.getChunksInRegion(HorseManager.java:246)
[17:58:30] [Thread-17/WARN]:    at eu.reborn_minecraft.zhorse.managers.HorseManager.access$0(HorseManager.java:238)
[17:58:30] [Thread-17/WARN]:    at eu.reborn_minecraft.zhorse.managers.HorseManager$1.run(HorseManager.java:180)
[17:58:30] [Thread-17/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns
[17:58:30] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.MCUtil.ensureMain(MCUtil.java:40)
[17:58:30] [Thread-17/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[17:58:30] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:158)
[17:58:30] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:141)
[17:58:30] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137)
[17:58:30] [Thread-17/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.getChunkAt(CraftWorld.java:149)
[17:58:30] [Thread-17/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.getChunkAt(CraftWorld.java:591)
[17:58:30] [Thread-17/WARN]:    at eu.reborn_minecraft.zhorse.managers.HorseManager.getChunksInRegion(HorseManager.java:246)
[17:58:30] [Thread-17/WARN]:    at eu.reborn_minecraft.zhorse.managers.HorseManager.access$0(HorseManager.java:238)
[17:58:30] [Thread-17/WARN]:    at eu.reborn_minecraft.zhorse.managers.HorseManager$1.run(HorseManager.java:180)
[17:58:30] [Thread-17/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns
[17:58:30] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.MCUtil.ensureMain(MCUtil.java:40)
[17:58:30] [Thread-17/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[17:58:30] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:158)
[17:58:30] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:141)
[17:58:30] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137)
[17:58:30] [Thread-17/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.getChunkAt(CraftWorld.java:149)
[17:58:30] [Thread-17/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.getChunkAt(CraftWorld.java:591)
[17:58:30] [Thread-17/WARN]:    at eu.reborn_minecraft.zhorse.managers.HorseManager.getChunksInRegion(HorseManager.java:246)
[17:58:30] [Thread-17/WARN]:    at eu.reborn_minecraft.zhorse.managers.HorseManager.access$0(HorseManager.java:238)
[17:58:30] [Thread-17/WARN]:    at eu.reborn_minecraft.zhorse.managers.HorseManager$1.run(HorseManager.java:180)
[17:58:30] [Thread-17/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns
[17:58:30] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.MCUtil.ensureMain(MCUtil.java:40)
[17:58:30] [Thread-17/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[17:58:30] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:158)
[17:58:30] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:141)
[17:58:30] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137)
[17:58:30] [Thread-17/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.getChunkAt(CraftWorld.java:149)
[17:58:30] [Thread-17/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.getChunkAt(CraftWorld.java:591)
[17:58:30] [Thread-17/WARN]:    at eu.reborn_minecraft.zhorse.managers.HorseManager.getChunksInRegion(HorseManager.java:246)
[17:58:30] [Thread-17/WARN]:    at eu.reborn_minecraft.zhorse.managers.HorseManager.access$0(HorseManager.java:238)
[17:58:30] [Thread-17/WARN]:    at eu.reborn_minecraft.zhorse.managers.HorseManager$1.run(HorseManager.java:180)
[17:58:30] [Thread-17/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns
[17:58:30] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.MCUtil.ensureMain(MCUtil.java:40)
[17:58:30] [Thread-17/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[17:58:30] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:158)
[17:58:30] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:141)
[17:58:30] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137)
[17:58:30] [Thread-17/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.getChunkAt(CraftWorld.java:149)
[17:58:30] [Thread-17/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.getChunkAt(CraftWorld.java:591)
[17:58:30] [Thread-17/WARN]:    at eu.reborn_minecraft.zhorse.managers.HorseManager.getChunksInRegion(HorseManager.java:246)
[17:58:30] [Thread-17/WARN]:    at eu.reborn_minecraft.zhorse.managers.HorseManager.access$0(HorseManager.java:238)
[17:58:30] [Thread-17/WARN]:    at eu.reborn_minecraft.zhorse.managers.HorseManager$1.run(HorseManager.java:180)
[17:58:30] [Thread-17/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns
[17:58:30] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.MCUtil.ensureMain(MCUtil.java:40)
[17:58:30] [Thread-17/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[17:58:30] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:158)
[17:58:30] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:141)
[17:58:30] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137)
[17:58:30] [Thread-17/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.getChunkAt(CraftWorld.java:149)
[17:58:30] [Thread-17/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.getChunkAt(CraftWorld.java:591)
[17:58:30] [Thread-17/WARN]:    at eu.reborn_minecraft.zhorse.managers.HorseManager.getChunksInRegion(HorseManager.java:246)
[17:58:30] [Thread-17/WARN]:    at eu.reborn_minecraft.zhorse.managers.HorseManager.access$0(HorseManager.java:238)
[17:58:30] [Thread-17/WARN]:    at eu.reborn_minecraft.zhorse.managers.HorseManager$1.run(HorseManager.java:180)
[17:58:31] [Thread-17/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns
[17:58:31] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.MCUtil.ensureMain(MCUtil.java:40)
[17:58:31] [Thread-17/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[17:58:31] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:158)
[17:58:31] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:141)
[17:58:31] [Thread-17/WARN]:    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137)
[17:58:31] [Thread-17/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.getChunkAt(CraftWorld.java:149)
[17:58:31] [Thread-17/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.getChunkAt(CraftWorld.java:591)
[17:58:31] [Thread-17/WARN]:    at eu.reborn_minecraft.zhorse.managers.HorseManager.getChunksInRegion(HorseManager.java:246)
[17:58:31] [Thread-17/WARN]:    at eu.reborn_minecraft.zhorse.managers.HorseManager.access$0(HorseManager.java:238)
[17:58:31] [Thread-17/WARN]:    at eu.reborn_minecraft.zhorse.managers.HorseManager$1.run(HorseManager.java:180)
```

**Comment by Zedd7** [comment]
Indeed, I should have removed that a long time ago.

**Comment by Zedd7** [comment]
Done since [bd5c3f](https://github.com/Xibalba/ZHorse/commit/bd5c3f436ce6d1472b8232451dc88f748ee94cc7)
